language: cpp
os: osx
osx_image: xcode9.3beta
branches:
  only:
  - SFML

before_install:
  - brew update && brew bundle

install:
  - git clone https://github.com/SFML/SFML.git
  - cd SFML
  - git checkout 2.4.2

before_script:
  - cat Doxyfile.patch >> SFML/doc/doxyfile.in

script:
  - mkdir SFML/build
  - cd SFML/build
  - cmake -D${docs}=TRUE ..
  - make doc
  - cd doc/html
  - make

before_deploy:
  - cd SFML/build/doc/html
  - wget ${http://icon.png}
  - convert ${icon.png} -resize 16x16! SFML.docset/icon.png
  - convert ${icon.png} -resize 32x32! SFML.docset/icon@2x.png
  - tar --exclude='.DS_Store' -cvzf SFML.tgz SFML.docset

deploy:
  provider: releases
  api_key:
    secure: RqFbiUdB6pegzmvEfD+tY3SCnYZ8AIDTB8ZJhvgTnCDG0vwkl63I3YGwdWpf4JbtG0M333pRxuaeIDSs/ncVQ9Qmj+lIzJXBZpYAehU0k8UyxRtf6BTC488xOpcIrux8JkrMSNrwhX5vTBk/c/S3dr64WbJJKIy5cVSoIt5EeWtSbjdjcxu5NKoHxRbzDdMJPPmFLad7se8bjuW839LWX7JucG2iGJ3jkYL+lsD0jAf7LVsrnW0iCoNDLWfYSNyrMDcXmfY7lWKV1bPx5AOOivgl65/lea1XAi7TKeq3uKlBd1rqer5+piWAayFg6pltDh+gCCebhdAGBvVhMApSR5Zouxe6/A+fyALSO8PAKDg6JuB17qijXwCRRc4dxnR/QYCw38dvUyQ00moqXiTiS0hURVJ4ew8xEH0pjuam9fj2o60+rWt+n5LnzrPyhA+r8OBeHz0hcXyyYbdH+WZAjBECBvFlBjkNQFvVlAyXvNR0gtkS1dStE6e6775/6IPbRDmWbYKN4PQplTS8mKdy6RR77zPdXhUpO3rZwrGYUjfATdI02boAqB/leOAJJXUTBlJ0EBTFSzOEqNcjs4JjSEKrwALPictZ/4Z4o19y/I0aK1xIL7u2x4FWMj9eXTCz1iri3Ha9392oYc5wwqwM9G2cSLbMWNOcq9n6NvHS0Mc=
  file:
    - "SFML/build/doc/html/SFML.tgz"
    - "SFML/build/doc/html/SFML.docset/icon.png"
    - "SFML/build/doc/html/SFML.docset/icon@2x.png"
    - "docset.json"
    - "README.md"
    - "SFML.xml"
  skip_cleanup: true
  on:
    repo: Eremiell/doxydash
    tags: true